### ISSUE TITLE
Use mount module instead of cmd

### ISSUE THREAD

**Issue by jrbalderrama** [msimonin/ombt-orchestrator#52] opened 2018-02-05 13:59 UTC
When executing the task 'mount' the following warning pops out:

`[WARNING]: Consider using mount module rather than running mount`

**Comment by msimonin** [comment] 2018-02-05 15:12
Actually in #33, I suspect that we can remove this.
This seems to be legacy code inherited from the openstack deployment with EnOS

**Comment by jrbalderrama** [comment] 2018-02-05 15:22
Indeed you can merge both tickets or declare this one as duplicate

**Comment by msimonin** [comment] 2018-02-05 15:36
Duplicate of #33 :)

**Closed by msimonin** 2018-02-05 15:36 UTC
